import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Pseudoartistas",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        <script src="/utils/theme.js"/>
        <link rel="apple-touch-icon" sizes="180x180" href="/media/img/logos/favicons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/media/img/logos/favicons/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/media/img/logos/favicons/favicon-16x16.png" />
        <link rel="manifest" href="/media/img/logos/favicons/site.webmanifest" />
        <link rel="mask-icon" href="/media/img/logos/favicons/safari-pinned-tab.svg" color="#fafafa" />
        <link rel="shortcut icon" href="/media/img/logos/favicons/favicon.ico" />
        <meta name="msapplication-TileColor" content="#fafafa" />
        <meta name="msapplication-config" content="/media/img/logos/favicons/browserconfig.xml" />
        <meta name="theme-color" content="#fafafa" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
